package: block_peek
version: '1.2.0'
license: MIT
author: Friends Of REDAXO, Yves Torres
supportpage: https://github.com/FriendsOfREDAXO/block_peek
perm: block_peek[]

page:
  title: 'translate:block_peek_title'
  icon: rex-icon fa-vr-cardboard
  perm: block_peek[]
  subpages:
    settings:
      title: 'translate:block_peek_settings'
      icon: rex-icon fa-cog
    docs:
      title: 'translate:block_peek_docs'
      subPath: README.md
      icon: rex-icon fa-book
      itemclass: pull-right

requires:
  redaxo: '^5.17.0'
  php:
    version: '>=8.2'

installer_ignore:
  - node_modules
  - assets-src
  - block_peek.zip
  - block_peek.png
  - scripts
  - .prettierrc
  - .stylelintrc.json
  - jsconfig.json
  - package.json
  - package-lock.json
  - postcss.config.js
  - vite.config.js
